# Generated by Django 5.2.5 on 2025-08-06 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Union',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('head_of_union', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('economic_code', models.CharField(max_length=50, unique=True)),
                ('fiscal_year', models.CharField(max_length=4)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('contact_info', models.CharField(max_length=11)),
                ('is_approved', models.BooleanField(default=False)),
                ('approval_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11)),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('union_name', models.CharField(max_length=200)),
                ('business_type', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('fiscal_year', models.CharField(max_length=4)),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='requests/')),
                ('is_approved', models.BooleanField(default=False)),
                ('approval_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('union', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='users.union')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11, unique=True)),
                ('national_id', models.CharField(max_length=10, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='union',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unions', to='users.userprofile'),
        ),
    ]
