# Generated by Django 5.2.5 on 2025-08-06 20:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='union',
            old_name='approval_comment',
            new_name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='union',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='union',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='union',
            name='audit_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('required', 'Required'), ('not_required', 'Not Required'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='union',
            name='financial_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='union',
            name='registration_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='union',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='union',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('union', 'Union'), ('admin', 'Admin')], default='union', max_length=20),
        ),
    ]
