# Generated by Django 5.2.5 on 2025-08-07 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_approval_comment_union_rejection_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='business_type',
        ),
        migrations.RemoveField(
            model_name='request',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='request',
            name='fiscal_year',
        ),
        migrations.RemoveField(
            model_name='request',
            name='province',
        ),
        migrations.RemoveField(
            model_name='request',
            name='union_name',
        ),
    ]
