# Generated by Django 5.2.5 on 2025-08-09 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_request_business_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='union',
            name='contact_info',
        ),
    ]
