# Generated by Django 5.2.5 on 2025-08-09 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_union_contact_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='union',
            old_name='economic_code',
            new_name='economicCode',
        ),
        migrations.RenameField(
            model_name='union',
            old_name='fiscal_year',
            new_name='fiscalYear',
        ),
        migrations.RenameField(
            model_name='union',
            old_name='head_of_union',
            new_name='headOfUnion',
        ),
    ]
